<?php

namespace Unicorn\Actions;

use Unicorn\Service\FS;

class SaveFile
{
    public function execute()
    {

        include_once (__DIR__ . '/../../../lib/scssphp/scss.inc.php');

        $request = json_decode(file_get_contents('php://input'), true);



        $id = $request['id'];
        $fs = FS::getInstance();

        $fileName = basename('/' . $id);

        $path = $fs->path($id);

        $content = $request['code'];

        if(strpos($path, '.scss') !== false && !str_starts_with($fileName, '_')) {
            $compiler = new \ScssPhp\ScssPhp\Compiler();

            $importPath = WP_CONTENT_DIR . str_replace('wp-content', '', dirname($path));
            $compiler->setImportPaths($importPath);
            $compiler->setImportPaths(dirname($path));



            $compiledCode = <<<EOD
/* Please do not edit this file directly. All changes will be lost. */


EOD;
            $compiledCode .= $compiler->compileString($content)->getCss();



            file_put_contents(substr($path, 0, strrpos($path, '.')) . '.css', $compiledCode);
        }


        file_put_contents($path, $content);

        echo json_encode([]);
		die;
    }
}
